kind: Service
apiVersion: v1
metadata:
  name: ozab-app
spec:  
  selector:
    run: ozab-app
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080